
# 如果使用本地文件，profiles.active需要是native，且searchLocations不能使用通配符

spring:
  cloud:
    config:
      server:
        native:
          searchLocations: file:C:\Code\mini-platform\config\config-repo  #申明本地配置文件的存放位置

eureka:
  client:
    service-url:
      defaultZone: http://discovery-dev:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
