server:
  port: 8088

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/mini_api_dev?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: hiling11

swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: 用户服务
  try-host: http://127.0.0.1:${server.port}